### ISSUE TITLE
[netrunner iso]: grub says "Netrunner Debian" after install, should say "Netrunner Core" versionnumber

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#11]

**Comment by shadeslayer** [comment]
@llelectronics Don't we have to update base-files for this? I thought we were going to copy over the debian packaging.

**Comment by llelectronics** [comment]
Yes base-files is the primary source for setting the name and version. Though also take a look at this modified 10_linux file for grub which takes the Name from GRUB_DISTRIBUTOR variable in the default grub config and the version from lsb_release. See: https://github.com/netrunner-common/netrunner-settings-grub/blob/master/etc/grub.d/10_linux#L110

**Comment by star-buck** [comment]
also "Netrunner Core (1)" in Calamares:
![distroversion screenshot_20160727_143208](https://cloud.githubusercontent.com/assets/840070/17179122/550468ee-5418-11e6-9f9c-8617c20461d3.png)

**Comment by star-buck** [comment]
also in Calamares general remove the word "Edition" (this also appears at the Welcome screen), simply "Netrunner Core":
![cala screenshot_20160727_143849](https://cloud.githubusercontent.com/assets/840070/17179244/c88c0ef2-5418-11e6-8f4a-3de2932f3a32.png)
