### ISSUE TITLE
[packaging]: add carbon widget packages (qt4, qt5, gtk2)

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#14]
add those packages in maui and netrunner, so carbon-qt4, -qt5 and -gtk2 are selectable:

https://github.com/ds9-extras/carbon-qt
https://github.com/ds9-extras/carbon-gtk2

**Comment by llelectronics** [comment]
Last time I checked they weren't compatible

**Comment by star-buck** [comment]
then we need to fix those who are not compatible

**Comment by star-buck** [comment]
so lets still package them, and also split gtk into gtk2 (those should basically always work), and gtk3 (which like gnome shell could break, therefore we have carbon-gtk-css

**Comment by llelectronics** [comment]
Uploaded carbon-qt, carbon-qt4 & carbon-gtk2 packages to maui repo. Updated maui-artwork to recommend those packages to be installed so user can choose to use them.
