### ISSUE TITLE
[folderview]: settings: right-click-menu: UNTICK "open in dolphin"

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#16]

**Comment by star-buck** [comment]
for maui: UNTICK "run command"

**Comment by llelectronics** [comment]
I don't see it being ticked in Maui in the first place.

**Comment by star-buck** [comment]
as folderview, i see it ticked. ill check the next iso... note that some things do change from live mode to after being installed...will look out for both instances next iso.

**Comment by star-buck** [comment]
@shadeslayer : it is still ticked in netrunner iso...

**Comment by shadeslayer** [comment]
@star-buck should be fixed in today's image

**Comment by star-buck** [comment]
netrunner-arm done, still need to confirm on iso
