### ISSUE TITLE
[maui-neon]: missing libroffice-calc, presentation (in menu?)

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#17]

**Comment by llelectronics** [comment]
Isn't that removed like on Netrunner17? If you don't want it to be removed I will adapt the list of packages that get removed

**Comment by star-buck** [comment]
No. The libreoffice suite was always listed completely, even in n17?
Only lo-draw could have been decided to hide from long time ago...

**Comment by star-buck** [comment]
build12 shows them again
