### ISSUE TITLE
[firefox bookmarks]: change "forum link" from https:// to http://

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#18]

**Comment by llelectronics** [comment]
Like I said in the irc I am strongly against it. 
We should provide secure SSL connections for our users especially for our forum.

**Comment by star-buck** [comment]
Yes, but it will be automatic go https if we switch it, so for now simply
link http and it will be https if enabled.

**Comment by llelectronics** [comment]
Should be fixed with latest maui-settings-firefox package
