### ISSUE TITLE
[kamoso]: package 3.2

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#21]
is the ISO build from scratch on neon or how did that old package end up in the ISO?

**Comment by llelectronics** [comment]
The package comes from Ubuntu. There is no newer one available on neon

**Comment by star-buck** [comment]
okay, synaptic says 3.0.0... 
i thought i recall kamoso being part of kde apps, but i ll check with Aleix on that tomorrow. maybe we need to package kamoso then ourselves?

**Comment by star-buck** [comment]
found it here: its standalone 3.2:
https://userbase.kde.org/Kamoso/3.2

**Comment by star-buck** [comment]
better: http://download.kde.org/stable/kamoso/3.2/src/kamoso-3.2.tar.xz.mirrorlist

**Comment by shadeslayer** [comment]
Package updated, please upgrade

**Comment by llelectronics** [comment]
Package added to Maui aswell.
