### ISSUE TITLE
[maui-1]: menu: list of things

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#24]
if choosing simplemenu or dash:
- [x] "additional drivers" entry no longer works (remove)
- [x] synaptic has double entry (remove one)
- [ ] "Discover" : remove or at least blend out from menu

**Comment by llelectronics** [comment]
Smells like a bug in simplemenu.

**Comment by star-buck** [comment]
nope, its even double in kicker

**Comment by llelectronics** [comment]
Additional Drivers does not work because it complains about missing aptdaemon python module. 
Instead of removing maybe we should fix this issue instead. 
Software-properties-gtk suffers in general from this issue.

**Comment by llelectronics** [comment]
Additional Drivers and software-properties-gtk removed in next ISO

**Comment by star-buck** [comment]
@llelectronics : please mark all solved by clicking them in first comment

**Comment by llelectronics** [comment]
Discover should be still visible and installed. Will change that for next ISO
