### ISSUE TITLE
[netrunner]: branding: list of things

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#27]
menu:

- [x] default switch to Dash

sddm themeing:

- [x] rename netrunner-core folder to breeze-new: https://github.com/ds9-artwork/artwork-sddm-breeze-new
- [x] build artwork-sddm-breeze-new from ds9-artwork, but dont include in netrunner
- [x] repackage and ship in netrunner (but not default) https://github.com/netrunner-artwork/artwork-sddm-netrunner-core with theme from here: https://www.dropbox.com/s/aaonlsxtlr14jlm/sddm-netrunner-core.zip?dl=0

----
plymouth:

- [x] change plymouth core: https://github.com/netrunner-artwork/artwork-plymouth-theme-netrunner/tree/master/usr/share/plymouth/themes/core with https://www.dropbox.com/s/gq0p1p1bapaxtql/plymouth-core.zip?dl=0

**Comment by star-buck** [comment]
- [ ] rename netrunner-core folder to breeze-new: https://github.com/ds9-artwork/artwork-sddm-breeze-new
- [ ] setup build artwork-sddm-breeze-new from ds9-artwork, but dont include in netrunner
- [ ] repackage and ship in netrunner (but not default) https://github.com/netrunner-artwork/artwork-sddm-netrunner-core with theme from here: https://www.dropbox.com/s/aaonlsxtlr14jlm/sddm-netrunner-core.zip?dl=0

**Comment by shadeslayer** [comment]
@star-buck everything fixed, dash changes should land in the next image

**Comment by star-buck** [comment]
@shadeslayer : please tick off then everything in first comment, also in the future whenever there is a list in first comment that can get expanded over time.
