### ISSUE TITLE
[about-kcm]: "Mesa 3D" on arm shows 0.0, maybe we need to probe another package instead?

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#35]
here is all packages that are installed on arm, so one clearly can see 10.3.2 is installed and used:
![snap 2016-07-29 at 18 35 13](https://cloud.githubusercontent.com/assets/840070/17255911/6ecff26c-55bb-11e6-9ae7-c3528cb558bc.png)

**Comment by shadeslayer** [comment]
@star-buck even though mesa 10.3.2 is installed, it's not used. We use the prorprietary mesa from ARM. This package is called mali-x11 IIRC.

This proprietary mesa doesn't actually properly report the version.

**Comment by star-buck** [comment]
okay, then lets leave it at 0.0
