### ISSUE TITLE
[maui-18]: shutdown from live mode hangs

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#36]

**Comment by llelectronics** [comment]
Works for me. 
Any error in ~/.xsession-errors for that matter ?

**Comment by star-buck** [comment]
ah, i didnt notice it hangsbecuase of the message to remove the stick (didnt expect that anymore for all the debian testing :)

**Comment by llelectronics** [comment]
Ah ok. We could prevent that with noprompt boot option if that is wanted.

**Comment by star-buck** [comment]
i guess its a feature, lets so leave it like that.
