### ISSUE TITLE
[maui-1]: ubiquity: replace maui slideshow

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#38]
slideshow for Maui: https://www.dropbox.com/s/0uvboi884a0gw5m/ubiquity-slideshow-maui-1.zip?dl=0

**Comment by star-buck** [comment]
slideshow for Maui: https://www.dropbox.com/s/0uvboi884a0gw5m/ubiquity-slideshow-maui-1.zip?dl=0

**Comment by llelectronics** [comment]
I think this sidebar image looks better. Do you agree ?

![newsidebar-color-ubiquity](https://cloud.githubusercontent.com/assets/3415572/17323969/82c03eda-58a4-11e6-9c29-2bc82f1db1e2.png)

**Comment by star-buck** [comment]
yep! :)
