### ISSUE TITLE
[systray]: UNTICK "Notifications" entry

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#40]
it is hidden, but not unticked

**Comment by star-buck** [comment]
it is hidden, but not unticked

**Comment by llelectronics** [comment]
Added a fix for maui-1

**Comment by star-buck** [comment]
build17: still TICKED in live mode (will install it now)

**Comment by llelectronics** [comment]
Needs scripting fix to work properly. 
I added it now also to the legacy panel creation script. So next ISO should have it no matter if scripting is fixed or not.
