### ISSUE TITLE
[maui-1]: correct versioning

### ISSUE THREAD

**Issue by star-buck** [maui-linux/issues#45]
- remove any numbers from top header, so it should simply read "Maui" or "Maui Linux"
- change version at bottom from 18 to "Maui 1 - Blue Tang"
![screenshot_20160802_213637](https://cloud.githubusercontent.com/assets/840070/17347080/4df0fe78-590e-11e6-9a54-98610766ec3f.png)

**Comment by llelectronics** [comment]
Removing version from the top header would mean removing the version string in the kcm-about source code itself. This will have an effect on maui-debian and netrunner-core aswell.

**Comment by star-buck** [comment]
Thats fine.
